apiVersion: v1
kind: Service
metadata:
  name: dd-zed-web-server
  namespace: zed
  labels:
    app: dd-zed-web-server
    app.kubernetes.io/part-of: zed
spec:
  type: ClusterIP
  selector:
    app: dd-zed-web-server
  ports:
    - name: http
      port: 8081
      targetPort: http
